name: Slash Command Dispatch

on:
  issue_comment:
    types: [created]

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.event.comment.user.login == 'luxass'
    steps:
      - uses: actions/checkout@v4

      - name: Slash Commands
        uses: peter-evans/slash-command-dispatch@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          commands: |
            release
          issue-type: pull-request
          permission: admin
